//
// Copyright © 2026 brzzdev
// SPDX-License-Identifier: AGPL-3.0-or-later
//

internal import ProjectDescription

// MARK: - Identity

let bundleIdentifier = "dev.brzz.SimpleRandom"

/// Read from the environment so nothing personal is committed; forks and CI supply their
/// own. Set `TUIST_DEVELOPMENT_TEAM` before `tuist generate`.
let developmentTeam = Environment.developmentTeam.getString(default: "")

// MARK: - Settings

/// The strict regime, second site. The first is the `for target in package.targets` loop
/// in `Package.swift`; the two exist because the modules compile through SwiftPM and this
/// target through Xcode. **The app shell is not exempt.**
///
/// Applied per target rather than at `Project(settings:)` on purpose: the local package is
/// integrated natively, so its targets build inside this project and a project-wide
/// `SWIFT_TREAT_WARNINGS_AS_ERRORS` would reach them.
var appTargetSettings: SettingsDictionary = [
	// `ImmutableWeakCaptures` is the one upcoming feature Xcode 26 exposes no
	// `SWIFT_UPCOMING_FEATURE_*` key for, so it goes through the raw flag.
	"OTHER_SWIFT_FLAGS": ["$(inherited)", "-enable-upcoming-feature", "ImmutableWeakCaptures"],
	"SWIFT_TREAT_WARNINGS_AS_ERRORS": "YES",
	"SWIFT_UPCOMING_FEATURE_EXISTENTIAL_ANY": "YES",
	"SWIFT_UPCOMING_FEATURE_INFER_ISOLATED_CONFORMANCES": "YES",
	"SWIFT_UPCOMING_FEATURE_INTERNAL_IMPORTS_BY_DEFAULT": "YES",
	"SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY": "YES",
	"SWIFT_UPCOMING_FEATURE_NONISOLATED_NONSENDING_BY_DEFAULT": "YES",
	"SWIFT_VERSION": "6.0",
]

if !developmentTeam.isEmpty {
	appTargetSettings["DEVELOPMENT_TEAM"] = .string(developmentTeam)
}

// MARK: - Project

let project = Project(
	name: "SimpleRandom",
	organizationName: "brzzdev",
	options: .options(
		// The scheme below is declared by hand so the test plan can be attached to it —
		// the four test targets live in the package, and nothing in this project depends
		// on them, so an autogenerated scheme would never build or run them. Letting Tuist
		// generate one too would collide on the name.
		automaticSchemesOptions: .disabled,
	),
	packages: [
		// The module graph lives in the root `Package.swift`. This layer holds only what
		// SwiftPM cannot express for a real `.app`.
		.package(path: "."),
	],
	targets: [
		.target(
			name: "SimpleRandom",
			destinations: [.iPhone],
			product: .app,
			bundleId: bundleIdentifier,
			deploymentTargets: .iOS("26.0"),
			infoPlist: .extendingDefault(with: [
				"CFBundleDisplayName": "SimpleRandom",
				"UILaunchScreen": [:],
			]),
			// AppHost renders no UI of its own — it exists to make `SimpleRandomApp`, which
			// lives in the package, the process entry point. That is also why no string
			// catalogue lives here: catalogues live where the text is (ADR-0022).
			sources: ["AppHost/**"],
			dependencies: [.package(product: "App")],
			settings: .settings(base: appTargetSettings),
		),
	],
	schemes: [
		.scheme(
			name: "SimpleRandom",
			shared: true,
			buildAction: .buildAction(targets: ["SimpleRandom"]),
			testAction: .testPlans(["SimpleRandom.xctestplan"]),
			runAction: .runAction(executable: "SimpleRandom"),
		),
	],
)
