//
// Copyright © 2026 brzzdev
// SPDX-License-Identifier: AGPL-3.0-or-later
//

internal import Foundation
internal import Models
internal import SQLiteData
internal import Testing

extension DatabaseTests {
	/// What a delete takes with it.
	///
	/// Deletes here are hard, immediate and global — there is no trash and no undo — so the
	/// blast radius of each one is a rule in its own right, and each test states the whole of
	/// it rather than checking the row it was aimed at.
	///
	/// `assertQuery` is deliberately not used. Its expectation is generated by running the
	/// code, so a cascade test written that way records what the schema *did* rather than
	/// what the rules say it must do, and a wrong `ON DELETE` goes green on re-record
	/// (ADR-0019).
	@Suite
	struct CascadeTests {
		@Test
		func deletingAListTakesItsItemsDrawsAndMembershipsWithIt() async throws {
			@Dependency(\.defaultDatabase) var database

			try await seedTwoListsInOneCombo(database)
			try await database.write { db in
				try Models.List.find(UUID(-1)).delete().execute(db)
			}

			// Films and its Item survive untouched; Lunch takes with it its Items, the draw
			// over one of them, its membership of Friday night, and the Combo's draw over its
			// Item. The Combo itself stays and silently shrinks — nothing warns first.
			#expect(
				try await Snapshot(database) == Snapshot(
					comboDraws: [UUID(-2)],
					comboLists: [UUID(-2)],
					combos: [UUID(-1)],
					items: [UUID(-3)],
					listDraws: [],
					lists: [UUID(-2)],
				)
			)
		}

		@Test
		func deletingAComboKeepsTheListsInIt() async throws {
			@Dependency(\.defaultDatabase) var database

			try await seedTwoListsInOneCombo(database)
			try await database.write { db in
				try Combo.find(UUID(-1)).delete().execute(db)
			}

			// A Combo is an arrangement of Lists, not an owner of them: its memberships and
			// its own deck go, and every List, Item and `ListDraw` is left exactly as it was.
			#expect(
				try await Snapshot(database) == Snapshot(
					comboDraws: [],
					comboLists: [],
					combos: [],
					items: [UUID(-1), UUID(-2), UUID(-3)],
					listDraws: [UUID(-1)],
					lists: [UUID(-1), UUID(-2)],
				)
			)
		}

		@Test
		func deletingAnItemTakesItsDrawsOnBothSurfacesWithIt() async throws {
			@Dependency(\.defaultDatabase) var database

			try await seedTwoListsInOneCombo(database)
			try await database.write { db in
				try Item.find(UUID(-1)).delete().execute(db)
			}

			// The two decks are independent of each other but not of the Item: a draw row is
			// keyed on the Item's identity, so removing the Item removes the fact that it was
			// dealt, on the List's surface and on the Combo's alike.
			#expect(
				try await Snapshot(database) == Snapshot(
					comboDraws: [UUID(-2)],
					comboLists: [UUID(-1), UUID(-2)],
					combos: [UUID(-1)],
					items: [UUID(-2), UUID(-3)],
					listDraws: [],
					lists: [UUID(-1), UUID(-2)],
				)
			)
		}

		/// Two Lists, both members of one Combo, with a draw already recorded on each
		/// surface — the smallest world in which every cascade in the schema has something to
		/// take and something to leave behind.
		private func seedTwoListsInOneCombo(_ database: any DatabaseWriter) async throws {
			let createdAt = Date(timeIntervalSince1970: 1_234_567_890)

			try await database.write { db in
				try db.seed {
					Models.List(id: UUID(-1), createdAt: createdAt, name: "Lunch")
					Models.List(id: UUID(-2), createdAt: createdAt, drawMode: .deck, name: "Films")

					Item(id: UUID(-1), createdAt: createdAt, listID: UUID(-1), title: "Pizza")
					Item(id: UUID(-2), createdAt: createdAt, listID: UUID(-1), title: "Ramen")
					Item(id: UUID(-3), createdAt: createdAt, listID: UUID(-2), title: "Alien")

					ListDraw(itemID: UUID(-1), createdAt: createdAt)

					Combo(id: UUID(-1), createdAt: createdAt, drawMode: .deck, name: "Friday night")
					ComboList(id: UUID(-1), comboID: UUID(-1), createdAt: createdAt, listID: UUID(-1))
					ComboList(id: UUID(-2), comboID: UUID(-1), createdAt: createdAt, listID: UUID(-2))

					ComboDraw(id: UUID(-1), comboID: UUID(-1), createdAt: createdAt, itemID: UUID(-1))
					ComboDraw(id: UUID(-2), comboID: UUID(-1), createdAt: createdAt, itemID: UUID(-3))
				}
			}
		}
	}
}

/// Every id in the database, by table. A cascade is a statement about the whole database
/// rather than about the row that was deleted, so this is what a cascade test asserts on.
private struct Snapshot: Equatable {
	let comboDraws: Set<UUID>
	let comboLists: Set<UUID>
	let combos: Set<UUID>
	let items: Set<UUID>
	let listDraws: Set<UUID>
	let lists: Set<UUID>

	init(
		comboDraws: Set<UUID>,
		comboLists: Set<UUID>,
		combos: Set<UUID>,
		items: Set<UUID>,
		listDraws: Set<UUID>,
		lists: Set<UUID>,
	) {
		self.comboDraws = comboDraws
		self.comboLists = comboLists
		self.combos = combos
		self.items = items
		self.listDraws = listDraws
		self.lists = lists
	}

	init(_ database: any DatabaseReader) async throws {
		self = try await database.read { db in
			try Self(
				comboDraws: Set(ComboDraw.all.fetchAll(db).map(\.id)),
				comboLists: Set(ComboList.all.fetchAll(db).map(\.id)),
				combos: Set(Combo.all.fetchAll(db).map(\.id)),
				items: Set(Item.all.fetchAll(db).map(\.id)),
				listDraws: Set(ListDraw.all.fetchAll(db).map(\.itemID)),
				lists: Set(Models.List.all.fetchAll(db).map(\.id)),
			)
		}
	}
}
