//
// Copyright © 2026 brzzdev
// SPDX-License-Identifier: AGPL-3.0-or-later
//

internal import Foundation
internal import Models
internal import SQLiteData
internal import Testing

extension DatabaseTests {
	/// What a delete takes with it.
	///
	/// Deletes here are hard, immediate and global — there is no trash and no undo — so the
	/// blast radius of each one is a rule in its own right, and each test states the whole of
	/// it rather than checking the row it was aimed at.
	///
	/// Each case seeds its own world inline, sized to the rule it asserts. There is no shared
	/// fixture: one would make these read as assertions about the fixture rather than about
	/// the domain, and the four worlds below genuinely differ (ADR-0019).
	///
	/// `assertQuery` is deliberately not used either. Its expectation is generated by running
	/// the code, so a cascade test written that way records what the schema *did* rather than
	/// what the rules say it must do, and a wrong `ON DELETE` goes green on re-record.
	@Suite
	struct CascadeTests {
		@Test
		func deletingAListTakesItsItemsDrawsAndMembershipsWithIt() async throws {
			@Dependency(\.defaultDatabase) var database

			// Two Lists, both members of one Combo, with a draw recorded on each surface.
			try await database.write { db in
				try db.seed {
					Models.List(id: UUID(-1), createdAt: .seed, name: "Lunch")
					Models.List(id: UUID(-2), createdAt: .seed, name: "Films")

					Item(id: UUID(-1), createdAt: .seed, listID: UUID(-1), title: "Pizza")
					Item(id: UUID(-2), createdAt: .seed, listID: UUID(-1), title: "Ramen")
					Item(id: UUID(-3), createdAt: .seed, listID: UUID(-2), title: "Alien")

					ListDraw(itemID: UUID(-1), createdAt: .seed)

					Combo(id: UUID(-1), createdAt: .seed, drawMode: .deck, name: "Friday night")
					ComboList(id: UUID(-1), comboID: UUID(-1), createdAt: .seed, listID: UUID(-1))
					ComboList(id: UUID(-2), comboID: UUID(-1), createdAt: .seed, listID: UUID(-2))

					ComboDraw(id: UUID(-1), comboID: UUID(-1), createdAt: .seed, itemID: UUID(-1))
					ComboDraw(id: UUID(-2), comboID: UUID(-1), createdAt: .seed, itemID: UUID(-3))
				}
			}

			try await database.write { db in
				try Models.List.find(UUID(-1)).delete().execute(db)
			}

			// Lunch takes with it its Items, the draw over one of them, its membership of
			// Friday night, and that Combo's draw over its Item. Films and its Item are
			// untouched, and the Combo itself stays and silently shrinks — nothing warns first.
			#expect(
				try await Snapshot(database) == Snapshot(
					comboDraws: [UUID(-2)],
					comboLists: [UUID(-2)],
					combos: [UUID(-1)],
					items: [UUID(-3)],
					listDraws: [],
					lists: [UUID(-2)],
				)
			)
		}

		@Test
		func deletingTheCountedListsAndCombosTakesEverythingUnderThemAndNothingElse() async throws {
			@Dependency(\.defaultDatabase) var database

			// What Settings' `Delete All Lists` runs against, plus a List and a Combo standing in
			// for rows that arrived after the dialog counted — a sync insert, most plausibly. The
			// gesture names ids rather than whole tables, so those two are not in what it deletes.
			try await database.write { db in
				try db.seed {
					Models.List(id: UUID(-1), createdAt: .seed, drawMode: .deck, name: "Lunch")
					Models.List(id: UUID(-2), createdAt: .seed, name: "Films")
					Models.List(id: UUID(-3), createdAt: .seed, name: "Arrived late")

					Item(id: UUID(-1), createdAt: .seed, listID: UUID(-1), title: "Pizza")
					Item(id: UUID(-2), createdAt: .seed, listID: UUID(-2), title: "Alien")
					Item(id: UUID(-3), createdAt: .seed, listID: UUID(-3), title: "Sushi")

					ListDraw(itemID: UUID(-1), createdAt: .seed)
					ListDraw(itemID: UUID(-3), createdAt: .seed)

					Combo(id: UUID(-1), createdAt: .seed, drawMode: .deck, name: "Friday night")
					Combo(id: UUID(-2), createdAt: .seed, name: "Also arrived late")

					ComboList(id: UUID(-1), comboID: UUID(-1), createdAt: .seed, listID: UUID(-1))
					ComboList(id: UUID(-2), comboID: UUID(-1), createdAt: .seed, listID: UUID(-2))
					ComboList(id: UUID(-3), comboID: UUID(-2), createdAt: .seed, listID: UUID(-3))

					ComboDraw(id: UUID(-1), comboID: UUID(-1), createdAt: .seed, itemID: UUID(-1))
					ComboDraw(id: UUID(-2), comboID: UUID(-2), createdAt: .seed, itemID: UUID(-3))
				}
			}

			// The two statements the feature runs, in the one transaction it runs them in.
			let countedLists = [UUID(-1), UUID(-2)]
			let countedCombos = [UUID(-1)]
			try await database.write { db in
				try Models.List.where { $0.id.in(countedLists) }.delete().execute(db)
				try Combo.where { $0.id.in(countedCombos) }.delete().execute(db)
			}

			// **Combos go with the Lists.** This is the one gesture that gets rid of everything,
			// and it is what separates it from deleting Lists one at a time — there a Combo stays
			// and silently shrinks, here it goes. Items, memberships and both kinds of draw row
			// follow whichever side owned them.
			//
			// **And nothing it did not count is touched.** The late List keeps its Item and its
			// draw, the late Combo keeps its membership and its own draw — a row arriving between
			// the counting and the deleting is not covered by the question that was asked, so the
			// delete has to name rows rather than tables for this half to hold.
			#expect(
				try await Snapshot(database) == Snapshot(
					comboDraws: [UUID(-2)],
					comboLists: [UUID(-3)],
					combos: [UUID(-2)],
					items: [UUID(-3)],
					listDraws: [UUID(-3)],
					lists: [UUID(-3)],
				)
			)
		}

		@Test
		func anItemArrivingIntoACountedListGoesWithItHoweverTheDialogCountedIt() async throws {
			@Dependency(\.defaultDatabase) var database

			// One List, counted with one Item in it.
			try await database.write { db in
				try db.seed {
					Models.List(id: UUID(-1), createdAt: .seed, name: "Lunch")
					Item(id: UUID(-1), createdAt: .seed, listID: UUID(-1), title: "Pizza")
				}
			}
			let countedLists = [UUID(-1)]

			// A second Item lands in that same List after the dialog counted it — a sync insert
			// arriving while the question is on screen. The dialog said one Item; there are now
			// two, and the confirmation cannot be narrowed to exclude the second.
			try await database.write { db in
				try db.seed {
					Item(id: UUID(-2), createdAt: .seed, listID: UUID(-1), title: "Ramen")
				}
			}

			try await database.write { db in
				try Models.List.where { $0.id.in(countedLists) }.delete().execute(db)
			}

			// **Both go, and that is the rule rather than a gap.** The Lists and Combos named by
			// the confirmation are exact — nothing outside them is touched — but an Item is not
			// named, it hangs off a List that is. Agreeing to delete a List is agreeing to
			// delete what is in it, so the Item count states how much is at stake at the moment
			// of asking rather than promising a number the cascade will match.
			//
			// The alternative was re-presenting the dialog whenever the count moved underneath,
			// which holds the number literally at the cost of a confirmation that can bounce
			// forever while another device is writing.
			#expect(
				try await Snapshot(database) == Snapshot(
					comboDraws: [],
					comboLists: [],
					combos: [],
					items: [],
					listDraws: [],
					lists: [],
				)
			)
		}

		@Test
		func deletingAComboKeepsTheListsInIt() async throws {
			@Dependency(\.defaultDatabase) var database

			// A Combo over two Lists, one of which has a draw of its own to be left alone.
			try await database.write { db in
				try db.seed {
					Models.List(id: UUID(-1), createdAt: .seed, drawMode: .deck, name: "Lunch")
					Models.List(id: UUID(-2), createdAt: .seed, name: "Films")

					Item(id: UUID(-1), createdAt: .seed, listID: UUID(-1), title: "Pizza")
					Item(id: UUID(-2), createdAt: .seed, listID: UUID(-2), title: "Alien")

					ListDraw(itemID: UUID(-1), createdAt: .seed)

					Combo(id: UUID(-1), createdAt: .seed, drawMode: .deck, name: "Friday night")
					ComboList(id: UUID(-1), comboID: UUID(-1), createdAt: .seed, listID: UUID(-1))
					ComboList(id: UUID(-2), comboID: UUID(-1), createdAt: .seed, listID: UUID(-2))

					ComboDraw(id: UUID(-1), comboID: UUID(-1), createdAt: .seed, itemID: UUID(-1))
				}
			}

			try await database.write { db in
				try Combo.find(UUID(-1)).delete().execute(db)
			}

			// A Combo is an arrangement of Lists, not an owner of them: its memberships and
			// its own deck go, and every List, Item and `ListDraw` is left exactly as it was.
			#expect(
				try await Snapshot(database) == Snapshot(
					comboDraws: [],
					comboLists: [],
					combos: [],
					items: [UUID(-1), UUID(-2)],
					listDraws: [UUID(-1)],
					lists: [UUID(-1), UUID(-2)],
				)
			)
		}

		@Test
		func deletingAnItemTakesItsDrawsOnBothSurfacesWithIt() async throws {
			@Dependency(\.defaultDatabase) var database

			// One List in one Combo, where both of its Items have been dealt on both surfaces
			// — so a sibling's draws are there to survive.
			try await database.write { db in
				try db.seed {
					Models.List(id: UUID(-1), createdAt: .seed, drawMode: .deck, name: "Lunch")

					Item(id: UUID(-1), createdAt: .seed, listID: UUID(-1), title: "Pizza")
					Item(id: UUID(-2), createdAt: .seed, listID: UUID(-1), title: "Ramen")

					ListDraw(itemID: UUID(-1), createdAt: .seed)
					ListDraw(itemID: UUID(-2), createdAt: .seed)

					Combo(id: UUID(-1), createdAt: .seed, drawMode: .deck, name: "Friday night")
					ComboList(id: UUID(-1), comboID: UUID(-1), createdAt: .seed, listID: UUID(-1))

					ComboDraw(id: UUID(-1), comboID: UUID(-1), createdAt: .seed, itemID: UUID(-1))
					ComboDraw(id: UUID(-2), comboID: UUID(-1), createdAt: .seed, itemID: UUID(-2))
				}
			}

			try await database.write { db in
				try Item.find(UUID(-1)).delete().execute(db)
			}

			// The two decks are independent of each other but not of the Item: a draw row is
			// keyed on the Item's identity, so removing the Item removes the fact that it was
			// dealt, on the List's surface and on the Combo's alike. Ramen keeps both of its.
			#expect(
				try await Snapshot(database) == Snapshot(
					comboDraws: [UUID(-2)],
					comboLists: [UUID(-1)],
					combos: [UUID(-1)],
					items: [UUID(-2)],
					listDraws: [UUID(-2)],
					lists: [UUID(-1)],
				)
			)
		}
	}
}

/// Every id in the database, by table. A cascade is a statement about the whole database
/// rather than about the row that was deleted, so this is what a cascade test asserts on.
private struct Snapshot: Equatable {
	let comboDraws: Set<UUID>
	let comboLists: Set<UUID>
	let combos: Set<UUID>
	let items: Set<UUID>
	let listDraws: Set<UUID>
	let lists: Set<UUID>
}

extension Snapshot {
	/// Read in one transaction, so what a test asserts on is one moment rather than six.
	init(_ database: any DatabaseReader) async throws {
		self = try await database.read { db in
			try Self(
				comboDraws: Set(ComboDraw.all.fetchAll(db).map(\.id)),
				comboLists: Set(ComboList.all.fetchAll(db).map(\.id)),
				combos: Set(Combo.all.fetchAll(db).map(\.id)),
				items: Set(Item.all.fetchAll(db).map(\.id)),
				listDraws: Set(ListDraw.all.fetchAll(db).map(\.itemID)),
				lists: Set(Models.List.all.fetchAll(db).map(\.id)),
			)
		}
	}
}
